# Generated by Django 5.2.3 on 2025-08-07 16:28

import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('recrutement', 'Recrutement - Trouvez les talents qui feront la différence dans votre organisation'), ('formation', 'Formation - Développez les compétences de vos équipes avec nos programmes sur mesure'), ('conseil_rh', 'Conseil RH - Optimisez votre gestion des ressources humaines avec notre expertise'), ('externalisation', 'Externalisation - Confiez-nous la gestion administrative de vos RH'), ('coaching', 'Coaching - Accompagnement personnalisé pour vos managers et talents'), ('audit_rh', 'Audit RH - Évaluez et améliorez vos processus RH')], max_length=50, unique=True)),
                ('nom', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('secteur_activite', models.CharField(max_length=255)),
                ('site_web', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('pays', models.CharField(blank=True, max_length=100)),
                ('taille_entreprise', models.CharField(blank=True, max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('approuvee', models.BooleanField(default=False)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('supprimer', 'Supprimée')], default='inactive', max_length=20)),
                ('rccm', models.CharField(blank=True, max_length=30, null=True, verbose_name='RCCM')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('accepte_cgv_cgu', models.BooleanField(default=False, verbose_name='Accepte les CG/PC')),
                ('date_acceptation_cgv_cgu', models.DateTimeField(blank=True, null=True, verbose_name="Date d'acceptation des CGV/CGU")),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_entreprises', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entreprise', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DemandeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Détails de votre demande')),
                ('pieces_jointes', models.FileField(blank=True, null=True, upload_to='demandes/pieces_jointes/')),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('proposition', 'Proposition initiale RH'), ('accepte', "Accepté par l'entreprise"), ('contre_proposition', 'Contre-proposition reçue'), ('refuse', "Refusé par l'entreprise"), ('actif', 'Actif'), ('termine', 'Terminé'), ('suspendu', 'Suspendu')], default='en_attente', max_length=50)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='entreprise.entreprise')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprise.servicerh')),
            ],
            options={
                'verbose_name': 'Demande de service',
                'verbose_name_plural': 'Demandes de service',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='FactureLibre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fichier_facture', models.FileField(upload_to=documents.models.chemin_document)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('date_reception', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('envoyee', 'Envoyée'), ('reçue', 'Reçue'), ('payee', 'Payée')], default='envoyee', max_length=20)),
                ('preuve_paiement', models.FileField(blank=True, null=True, upload_to='documents/preuves_paiement/')),
                ('commentaire_entreprise', models.TextField(blank=True)),
                ('tva', models.DecimalField(decimal_places=2, default=18.0, max_digits=4, verbose_name='Taux de TVA (%)')),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant HT')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures_libres', to='entreprise.entreprise')),
                ('envoyee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_envoyees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('conditions', models.TextField(blank=True, verbose_name='Conditions particulières')),
                ('reponse_entreprise', models.TextField(blank=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tva', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('periodicite_facturation', models.CharField(choices=[('mensuelle', 'Mensuelle'), ('trimestrielle', 'Trimestrielle'), ('ponctuelle', 'Ponctuelle')], default='mensuelle', max_length=45)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de proposition'), ('proposition_envoyee', 'Proposition envoyée par Antares'), ('en_revue', 'En revue par le client'), ('accepte', 'Accepté par le client'), ('contre_proposition', 'Contre-proposition envoyée'), ('refuse', 'Refusé par Antares'), ('valide', 'Contre-proposition acceptée par Antares'), ('en_cours', 'En cours de traitement '), ('actif', 'Service actif'), ('suspendu', 'Service suspendu'), ('termine', 'Service terminé')], default='proposition', max_length=50)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_activation', models.DateTimeField(blank=True, null=True)),
                ('date_expiration', models.DateTimeField(blank=True, null=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('notes_interne', models.TextField(blank=True)),
                ('contre_proposition', models.TextField(blank=True, null=True)),
                ('demandes', models.ManyToManyField(blank=True, related_name='services_lies', to='entreprise.demandeservice')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='entreprise.entreprise')),
                ('responsable_rh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_geres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service personnalisé',
                'verbose_name_plural': 'Services personnalisés',
                'ordering': ['-date_activation'],
            },
        ),
        migrations.CreateModel(
            name='NotificationEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('reponse_entreprise', models.TextField(blank=True, null=True)),
                ('date_reponse', models.DateTimeField(blank=True, null=True)),
                ('niveau', models.CharField(choices=[('info', 'Info'), ('alerte', 'Alerte'), ('urgent', 'Urgent')], default='info', max_length=20)),
                ('fichier', models.FileField(blank=True, null=True, upload_to=documents.models.chemin_document)),
                ('lu', models.BooleanField(default=False)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('action_requise', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('client', 'Entreprise'), ('backoffice', 'Antares')], default='client', max_length=10)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='entreprise.entreprise')),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='entreprise.facturelibre')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='entreprise.serviceentreprise')),
            ],
        ),
        migrations.AddField(
            model_name='facturelibre',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='entreprise.serviceentreprise'),
        ),
    ]
