# Generated by Django 5.2.3 on 2025-07-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='adresse',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='pays',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='taille_entreprise',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='ville',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='secteur_activite',
            field=models.CharField(max_length=255),
        ),
    ]
