# Generated by Django 5.2.3 on 2025-07-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0002_alter_entreprise_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='statut',
            field=models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active'), ('supprimee', 'Supprimée')], default='non_active', max_length=20),
        ),
    ]
