# Generated by Django 5.2.3 on 2025-07-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0002_entreprise_adresse_entreprise_logo_entreprise_pays_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='rccm',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
