# Generated by Django 5.2.3 on 2025-07-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0003_entreprise_rccm'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='statut',
            field=models.CharField(choices=[('non_active', 'Non active'), ('active', 'Active'), ('pause', 'En pause'), ('terminee', 'Terminée')], default='non_active', max_length=20),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='rccm',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='RCCM'),
        ),
    ]
