# Generated by Django 5.2.3 on 2025-07-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0004_alter_entreprise_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='statut',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('supprimer', 'Supprimer')], default='non_active', max_length=20),
        ),
    ]
