# Generated by Django 5.2.3 on 2025-07-31 15:13

import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0006_alter_entreprise_statut'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationentreprise',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to=documents.models.chemin_document),
        ),
        migrations.AlterField(
            model_name='facturelibre',
            name='envoyee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_envoyees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facturelibre',
            name='fichier_facture',
            field=models.FileField(upload_to=documents.models.chemin_document),
        ),
        migrations.AlterField(
            model_name='facturelibre',
            name='preuve_paiement',
            field=models.FileField(blank=True, null=True, upload_to='documents/preuves_paiement/'),
        ),
    ]
