# Generated by Django 5.2.3 on 2025-07-31 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0007_notificationentreprise_fichier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceentreprise',
            name='demandes',
            field=models.ManyToManyField(blank=True, related_name='services_entreprise', to='entreprise.demandeservice'),
        ),
    ]
