# Generated by Django 5.2.3 on 2025-08-01 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0008_serviceentreprise_demandes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demandeservice',
            options={'ordering': ['-date_demande'], 'verbose_name': 'Demande de service', 'verbose_name_plural': 'Demandes de service'},
        ),
        migrations.AlterModelOptions(
            name='serviceentreprise',
            options={'ordering': ['-date_activation'], 'verbose_name': 'Service personnalisé', 'verbose_name_plural': 'Services personnalisés'},
        ),
        migrations.RemoveField(
            model_name='serviceentreprise',
            name='actif',
        ),
        migrations.RemoveField(
            model_name='serviceentreprise',
            name='demandes',
        ),
        migrations.AddField(
            model_name='demandeservice',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='demandeservice',
            name='pieces_jointes',
            field=models.FileField(blank=True, null=True, upload_to='demandes/pieces_jointes/'),
        ),
        migrations.AddField(
            model_name='serviceentreprise',
            name='conditions',
            field=models.TextField(blank=True, verbose_name='Conditions particulières'),
        ),
        migrations.AddField(
            model_name='serviceentreprise',
            name='date_activation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceentreprise',
            name='date_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceentreprise',
            name='demande_origine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_crees', to='entreprise.demandeservice'),
        ),
        migrations.AddField(
            model_name='serviceentreprise',
            name='notes_interne',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='serviceentreprise',
            name='periodicite_facturation',
            field=models.CharField(choices=[('mensuelle', 'Mensuelle'), ('trimestrielle', 'Trimestrielle'), ('ponctuelle', 'Ponctuelle')], default='mensuelle', max_length=20),
        ),
        migrations.AddField(
            model_name='serviceentreprise',
            name='responsable_rh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_geres', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceentreprise',
            name='statut',
            field=models.CharField(choices=[('proposition', 'Proposition RH'), ('en_revue', "En revue par l'entreprise"), ('actif', 'Actif'), ('rejete', "Rejeté par l'entreprise"), ('suspendu', 'Suspendu')], default='proposition', max_length=20),
        ),
        migrations.AddField(
            model_name='serviceentreprise',
            name='tva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='servicerh',
            name='code',
            field=models.CharField(choices=[('recrutement', 'Recrutement - Trouvez les talents qui feront la différence dans votre organisation'), ('formation', 'Formation - Développez les compétences de vos équipes avec nos programmes sur mesure'), ('conseil_rh', 'Conseil RH - Optimisez votre gestion des ressources humaines avec notre expertise'), ('externalisation', 'Externalisation - Confiez-nous la gestion administrative de vos RH'), ('coaching', 'Coaching - Accompagnement personnalisé pour vos managers et talents'), ('audit_rh', 'Audit RH - Évaluez et améliorez vos processus RH')], default='', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='demandeservice',
            name='message',
            field=models.TextField(verbose_name='Détails de votre demande'),
        ),
        migrations.AlterField(
            model_name='serviceentreprise',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicerh',
            name='nom',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
