# Generated by Django 5.2.3 on 2025-08-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0009_alter_demandeservice_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceentreprise',
            name='demande_origine',
        ),
        migrations.AddField(
            model_name='serviceentreprise',
            name='demandes',
            field=models.ManyToManyField(blank=True, related_name='services_lies', to='entreprise.demandeservice'),
        ),
    ]
