# Generated by Django 5.2.3 on 2025-08-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0010_remove_serviceentreprise_demande_origine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationentreprise',
            name='source',
            field=models.CharField(choices=[('client', 'Entreprise'), ('backoffice', 'Antares')], default='client', max_length=10),
        ),
    ]
