# Generated by Django 5.2.3 on 2025-08-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0011_notificationentreprise_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceentreprise',
            name='contre_proposition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceentreprise',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours de prestation'), ('proposition', 'Proposition RH'), ('rejete', "Rejeté par l'entreprise"), ('en_revue', "En revue par l'entreprise"), ('accepte', "Accepté par l'entreprise"), ('actif', 'Actif'), ('termine', 'Terminé'), ('suspendu', 'Suspendu')], default='proposition', max_length=20),
        ),
    ]
