# Generated by Django 5.2.3 on 2025-08-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0012_serviceentreprise_contre_proposition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceentreprise',
            name='periodicite_facturation',
            field=models.CharField(choices=[('mensuelle', 'Mensuelle'), ('trimestrielle', 'Trimestrielle'), ('ponctuelle', 'Ponctuelle')], default='mensuelle', max_length=45),
        ),
        migrations.AlterField(
            model_name='serviceentreprise',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours de prestation'), ('proposition', 'Proposition RH'), ('rejete', "Rejeté par l'entreprise"), ('en_revue', "En revue par l'entreprise"), ('en_attente_activation', 'En attente activation'), ('accepte', "Accepté par l'entreprise"), ('actif', 'Actif'), ('termine', 'Terminé'), ('suspendu', 'Suspendu')], default='proposition', max_length=50),
        ),
    ]
