# Generated by Django 5.2.3 on 2025-08-05 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0013_alter_serviceentreprise_periodicite_facturation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationentreprise',
            name='date_reponse',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationentreprise',
            name='facture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='entreprise.facturelibre'),
        ),
        migrations.AddField(
            model_name='notificationentreprise',
            name='reponse_entreprise',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationentreprise',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='entreprise.serviceentreprise'),
        ),
        migrations.AddField(
            model_name='serviceentreprise',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceentreprise',
            name='reponse_entreprise',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='serviceentreprise',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours de prestation'), ('proposition', 'Proposition RH'), ('rejete', "Rejeté par l'entreprise"), ('en_revue', "En revue par l'entreprise"), ('en_attente_activation', 'En attente activation'), ('accepte', "Accepté par l'entreprise"), ('actif', 'Actif'), ('termine', 'Terminé'), ('suspendu', 'Suspendu'), ('contre_proposition', 'Contre-proposition reçue'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='proposition', max_length=50),
        ),
    ]
