# Generated by Django 5.2.3 on 2025-07-31 15:13

import django.db.models.deletion
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('entreprise', '0007_notificationentreprise_fichier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='entreprise.entreprise'),
        ),
        migrations.AlterField(
            model_name='document',
            name='fichier',
            field=models.FileField(upload_to=documents.models.chemin_document),
        ),
    ]
