# Generated by Django 5.2.3 on 2025-07-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_skill_user_contract_file_user_contract_type_user_cv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cv_recruteur',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
        migrations.AddField(
            model_name='user',
            name='description_entreprise',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='domaines_recherche',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fonction_recruteur',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='niveau_etude',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='nom_entreprise',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='secteur_activite',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='site_web',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('rh', 'Ressources Humaines'), ('employe', 'Employé'), ('stagiaire', 'Stagiaire'), ('entreprise', 'Entreprise'), ('recruteur', 'Recruteur'), ('candidat', 'Candidat')], max_length=20),
        ),
    ]
