# Generated by Django 5.2.3 on 2025-07-24 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_cv_recruteur_user_description_entreprise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='description_entreprise',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nom_entreprise',
        ),
        migrations.RemoveField(
            model_name='user',
            name='secteur_activite',
        ),
        migrations.RemoveField(
            model_name='user',
            name='site_web',
        ),
    ]
