# Generated by Django 5.2.3 on 2025-08-07 16:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('titre', models.CharField(max_length=255)),
                ('type_offre', models.CharField(choices=[('emploi', "Offre d'emploi"), ('appel_offre', "Appel d'offres"), ('autre', 'Autre')], default='emploi', max_length=20)),
                ('mission_principale', models.TextField()),
                ('taches', models.TextField()),
                ('profil_recherche', models.TextField()),
                ('conditions', models.TextField(blank=True, null=True)),
                ('autres_infos', models.TextField(blank=True, null=True)),
                ('lieu', models.CharField(blank=True, max_length=255, null=True)),
                ('date_publication', models.DateField(default=django.utils.timezone.now)),
                ('date_limite', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('expire', 'Expiré'), ('archive', 'Archivé')], default='brouillon', max_length=20)),
                ('visible_sur_site', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('secteur', models.CharField(blank=True, max_length=255)),
                ('salaire', models.CharField(blank=True, max_length=100)),
                ('niveau_etude', models.CharField(blank=True, max_length=100)),
                ('experience_requise', models.CharField(blank=True, max_length=100)),
                ('contact', models.EmailField(blank=True, max_length=254)),
                ('fichier_pdf', models.FileField(blank=True, upload_to='offres_pdfs/')),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_publication'],
            },
        ),
    ]
