# Generated by Django 5.2.3 on 2025-08-07 19:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joboffer',
            options={'ordering': ['-date_publication'], 'verbose_name': "Offre d'emploi", 'verbose_name_plural': "Offres d'emploi"},
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='autres_infos',
        ),
        migrations.AddField(
            model_name='joboffer',
            name='comment_postuler',
            field=models.TextField(default='', help_text='Instructions pour postuler', verbose_name='Comment postuler'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joboffer',
            name='competences_qualifications',
            field=models.TextField(blank=True, help_text='Liste des compétences requises', null=True, verbose_name='Compétences et qualifications'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='description_poste',
            field=models.TextField(default='', help_text='Description générale du poste', verbose_name='Description du poste'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joboffer',
            name='societe',
            field=models.CharField(default='', help_text="Nom de l'entreprise ou organisation proposant l'offre", max_length=255, verbose_name='Société/Organisation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='conditions',
            field=models.TextField(blank=True, help_text='Conditions particulières ', null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='contact',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email de contact'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='date_limite',
            field=models.DateField(blank=True, null=True, verbose_name='Date limite de candidature'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='date_publication',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date de publication'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='experience_requise',
            field=models.CharField(blank=True, help_text='5 ans minimun en gestion ', max_length=100, verbose_name="Nombre d'année expérience requise"),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='fichier_pdf',
            field=models.FileField(blank=True, upload_to='offres_pdfs/', verbose_name="PDF de l'offre"),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='lieu',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lieu de travail'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='mission_principale',
            field=models.TextField(blank=True, help_text='Missions principales', null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='niveau_etude',
            field=models.CharField(blank=True, max_length=100, verbose_name="Niveau d'étude requis"),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='profil_recherche',
            field=models.TextField(help_text='Description du profil idéal', verbose_name='Profil recherché'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='reference',
            field=models.CharField(help_text='Référence unique commençant par ANT/STA (ex: ANT/STA/00002025)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='salaire',
            field=models.CharField(blank=True, max_length=100, verbose_name='Salaire/Indemnité'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='secteur',
            field=models.CharField(blank=True, max_length=255, verbose_name="Secteur d'activité"),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='taches',
            field=models.TextField(blank=True, help_text='Tâches spécifiques', null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='titre',
            field=models.CharField(max_length=255, verbose_name='Titre du poste'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='visible_sur_site',
            field=models.BooleanField(default=True, verbose_name='Visible sur le site'),
        ),
    ]
