# Generated by Django 5.2.3 on 2025-08-07 21:04

import django.db.models.deletion
import django_summernote.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_joboffer_options_remove_joboffer_autres_infos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joboffer',
            options={'ordering': ['-date_publication'], 'permissions': [('can_publish_offer', 'Peut publier une offre'), ('can_manage_offer', 'Peut gérer toutes les offres')], 'verbose_name': "Offre d'emploi", 'verbose_name_plural': "Offres d'emploi"},
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='competences_qualifications',
            field=models.TextField(blank=True, help_text='Liste des compétences requises (une par ligne)', null=True, verbose_name='Compétences et qualifications'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='conditions',
            field=models.TextField(blank=True, help_text='Conditions particulières (une par ligne)', null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='experience_requise',
            field=models.CharField(blank=True, help_text="Ex: '3 ans minimum en développement web'", max_length=100, verbose_name='Expérience requise'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='fichier_pdf',
            field=models.FileField(blank=True, help_text='Format PDF uniquement', upload_to='offres_pdfs/', verbose_name="PDF de l'offre"),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='mission_principale',
            field=models.TextField(blank=True, help_text='Missions principales (une par ligne)', null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='taches',
            field=models.TextField(blank=True, help_text='Tâches spécifiques (une par ligne)', null=True),
        ),
        migrations.CreateModel(
            name='SummernoteAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Defaults to filename, if left blank', max_length=255, null=True)),
                ('file', models.FileField(upload_to=django_summernote.utils.uploaded_filepath)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='jobs.joboffer')),
            ],
            options={
                'verbose_name': 'Pièce jointe',
                'verbose_name_plural': 'Pièces jointes',
            },
        ),
    ]
