# Generated by Django 5.2.3 on 2025-08-08 09:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_joboffer_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='nombre_candidat',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
