# Generated by Django 5.2.3 on 2025-08-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_joboffer_nombre_candidat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joboffer',
            name='description_poste',
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='experience_requise',
            field=models.CharField(blank=True, help_text='Ex: 3 ans minimum en développement web', max_length=100, verbose_name='Expérience requise'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='societe',
            field=models.CharField(default='Antares', help_text="Nom de l'entreprise ou organisation proposant l'offre", max_length=255, verbose_name='Société/Organisation'),
        ),
    ]
