# Generated by Django 5.2.3 on 2025-08-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_remove_joboffer_description_poste_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='reference',
            field=models.CharField(help_text='Référence unique commençant par ANT/ (ex: ANT/)', max_length=100, unique=True),
        ),
    ]
