# Generated by Django 5.2.3 on 2025-08-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_joboffer_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joboffer',
            name='nombre_candidat',
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='experience_requise',
            field=models.CharField(blank=True, help_text="Ex: '3 ans minimum en développement web'", max_length=100, verbose_name='Expérience requise'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='reference',
            field=models.CharField(help_text='Référence unique commençant par ANT/STA (ex: ANT/STA/00002025)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='societe',
            field=models.CharField(help_text="Nom de l'entreprise ou organisation proposant l'offre", max_length=255, verbose_name='Société/Organisation'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('expire', 'Expiré'), ('archive', 'Archivé')], default='brouillon', max_length=20),
        ),
    ]
