# Generated by Django 5.2.3 on 2025-08-09 21:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_remove_joboffer_nombre_candidat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joboffer',
            options={'ordering': ['-date_publication'], 'verbose_name': "Offre d'emploi", 'verbose_name_plural': "Offres d'emploi"},
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='comment_postuler',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='competences_qualifications',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='conditions',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='contact',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='date_limite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='date_publication',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='experience_requise',
            field=models.CharField(blank=True, help_text="Ex: '3 ans minimum'", max_length=100, verbose_name='Expérience requise'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='fichier_pdf',
            field=models.FileField(blank=True, upload_to='offres_pdfs/'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='lieu',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='mission_principale',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='profil_recherche',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='reference',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='salaire',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='secteur',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='societe',
            field=models.CharField(default='Antares', max_length=255),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='taches',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='titre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='visible_sur_site',
            field=models.BooleanField(default=True),
        ),
    ]
