# Generated by Django 5.2.3 on 2025-08-09 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_alter_joboffer_options_alter_joboffer_auteur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='nombre_candidat',
            field=models.PositiveIntegerField(default=1, verbose_name='Nombre de candidats'),
        ),
    ]
