# Generated by Django 5.2.3 on 2025-08-09 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_joboffer_nombre_candidat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('ouvert', 'Ouvert'), ('expire', 'Expiré'), ('archive', 'Archivé')], default='brouillon', max_length=20),
        ),
    ]
